package de.robinschleser.the12lords.input.gamepad;

public enum GamePadAxis {

    LEFT_AXIS_BIT_DOWN,
    LEFT_AXIS_MEDIUM_DOWN,
    LEFT_AXIS_DOWN,

    LEFT_AXIS_BIT_UP,
    LEFT_AXIS_MEDIUM_UP,
    LEFT_AXIS_UP,

    LEFT_AXIS_BIT_LEFT,
    LEFT_AXIS_MEDIUM_LEFT,
    LEFT_AXIS_LEFT,

    LEFT_AXIS_BIT_RIGHT,
    LEFT_AXIS_MEDIUM_RIGHT,
    LEFT_AXIS_RIGHT,




    RIGHT_AXIS_BIT_DOWN,
    RIGHT_AXIS_MEDIUM_DOWN,
    RIGHT_AXIS_DOWN,

    RIGHT_AXIS_BIT_UP,
    RIGHT_AXIS_MEDIUM_UP,
    RIGHT_AXIS_UP,

    RIGHT_AXIS_BIT_LEFT,
    RIGHT_AXIS_MEDIUM_LEFT,
    RIGHT_AXIS_LEFT,

    RIGHT_AXIS_BIT_RIGHT,
    RIGHT_AXIS_MEDIUM_RIGHT,
    RIGHT_AXIS_RIGHT

}
